# TARGETS: name for certain operations you want to assign

build:
	gcc main.c -c main.o
	gcc main.o -o main # we can list as many commands as we want 

run:
	./main

# target: prerequisites which is the dependency to the target

